<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<a href="D:\workspace\mycore\screenshotimg\2015-12-23-15-37-41testlogin.png" target="_blank">Failed Screen Shot</a>]]>
    </line>
    <line>
      <![CDATA[<a href="D:\workspace\mycore\screenshotimg\2015-12-23-15-37-48testlogin.png" target="_blank">Failed Screen Shot</a>]]>
    </line>
    <line>
      <![CDATA[<a href="D:\workspace\mycore\screenshotimg\2015-12-23-15-37-48testlogin.png" target="_blank">Failed Screen Shot</a>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="12797" started-at="2015-12-23T07:37:36Z" finished-at="2015-12-23T07:37:49Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="12797" started-at="2015-12-23T07:37:36Z" finished-at="2015-12-23T07:37:49Z">
      <class name="com.core.testcase.TestLogin">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.core.testcase.TestLogin@3f80cfa7]" name="beforeClass" is-config="true" duration-ms="2643" started-at="2015-12-23T15:37:36Z" finished-at="2015-12-23T15:37:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.core.testcase.TestLogin@3f80cfa7]" name="afterClass" is-config="true" duration-ms="1369" started-at="2015-12-23T15:37:42Z" finished-at="2015-12-23T15:37:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.core.testcase.TestLogin@3f80cfa7]" name="beforeClass" is-config="true" duration-ms="2341" started-at="2015-12-23T15:37:43Z" finished-at="2015-12-23T15:37:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="testlogin()[pri:0, instance:com.core.testcase.TestLogin@3f80cfa7]" name="testlogin" duration-ms="2269" started-at="2015-12-23T15:37:45Z" finished-at="2015-12-23T15:37:48Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at com.core.testcase.TestLogin.testlogin(TestLogin.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
            <line>
              <![CDATA[<a href="D:\workspace\mycore\screenshotimg\2015-12-23-15-37-48testlogin.png" target="_blank">Failed Screen Shot</a>]]>
            </line>
            <line>
              <![CDATA[<a href="D:\workspace\mycore\screenshotimg\2015-12-23-15-37-48testlogin.png" target="_blank">Failed Screen Shot</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- testlogin -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.core.testcase.TestLogin@3f80cfa7]" name="afterClass" is-config="true" duration-ms="1270" started-at="2015-12-23T15:37:48Z" finished-at="2015-12-23T15:37:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.core.testcase.TestLogin -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
